### ISSUE TITLE
Implement Bootstrap

### ISSUE THREAD

**Issue by kolja-lucht** [ruby-stars/community-calendar#37]
Implement bootstrap with the project
https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by kajatiger** [comment]
I was also trying to implement haml (it's nicer to code the views with it than erb), but then I ran into ssh problems and couldn't push my suggestions. But you could check it out [here](https://github.com/haml/haml-rails).
And here is a [tutorial](http://haml.info/tutorial.html) how to use it. It's really simple and you can skip all these weird `<%` signs ☺️
