### ISSUE TITLE
watch git tutorial

### ISSUE THREAD

**Issue by yakamozzz** [ruby-stars/community-calendar#8]
https://www.codecademy.com/learn/learn-git 
Who finished?
- [x] Myri
- [x] Celeste
- [x] Kolja
- [x] Anne

**Comment by clstrex** [comment]
On it :)

**Comment by kolja-lucht** [comment]
@annesbln This little track on codecademy about git is quite helpful. Maybe you feel like checking it out, too.

**Comment by annesbln** [comment]
Thank you @kolja-lucht for this very useful intro. I completed it today and there are so many very useful commands mentioned in it. I really want to use this more often at work. Unfortunately we use a UI-based git program which makes us a bit lazy. But I definitely want to learn more about the terminal commands :+1:  I also learned NOT to to push into master *sobbes a bit embarrassed*
